rm(list=ls())

if (FALSE){
    setwd('/home/pvermees/Dropbox/Programming/R/IsoplotR/R')
    source("ArAr.R")
    source("age.R")
    source("agespectrum.R")
    source("botev.R")
    source("cad.R")
    source("central.R")
    source("ci.R")
    source("commonPb.R")
    source("concordia.R")
    source("constants.R")
    source("discordia.R")
    source("errorellipse.R")
    source("evolution.R")
    source("fissiontracks.R")
    source("helioplot.R")
    source("io.R")
    source("isochron.R")
    source("json.R")
    source("kde.R")
    source("ludwig.R")
    source("LuHf.R")
    source("mds.R")
    source("peakfit.R")
    source("PD.R")
    source("PbPb.R")
    source("radialplot.R")
    source("regression.R")
    source("ReOs.R")
    source("RbSr.R")
    source("SmNd.R")
    source("ThU.R")
    source("titterington.R")
    source("toolbox.R")
    source("UPb.R")
    source("UThHe.R")
    source("weightedmean.R")
    source("york.R")
    settings(fname="../inst/constants.json")

    FT <- read.data('/home/pvermees/Dropbox/Programming/R/fissiontracks/FTdata.csv',method='fissiontracks',format=1)
    fit <- peakfit(FT,k=2)

} else {
    setwd('/home/pvermees/Dropbox/Programming/R/fissiontracks')
    source('multirad.R')
    
    FT1 <- read.data('FT1.csv',method='fissiontracks',format=1)
    FT2 <- read.data('FT2.csv',method='fissiontracks',format=1)
    FT <- FTpool(FT1,FT2)
    fit <- peakfit(FT,k=2)
}
